shell.run("pastebin get wPtGKMam github")
shell.run("github OwOsucksAwesomeMinecraftbossAlissha6TRM computerCraftPrograms . AweOS/AweOS")
fs.move("downloads/computerCraftPrograms/AweOS/AweOS", "AweOS/")
file = fs.open("startup.lua","w")
file.write("shell.run('AweOS/PasswordSys.lua')")
file.close()
fs.delete("downloads/")
