shell.run("pastebin get wPtGKMam github")
shell.run("github OwOsucksAwesomeMinecraftbossAlissha6TRM computerCraftPrograms . AweOS/AweOS")
fs.move("downloads/computerCraftPrograms/AweOS/AweOS", "AweOS/")
shell.run("github OwOsucksAwesomeMinecraftbossAlissha6TRM computerCraftPrograms . AweOSInstaller/")
fs.move("downloads/computerCraftPrograms/AweOSInstaller/startup.lua","startup")
fs.delete("downloads/")
